version: '3.8'
services:
  db:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
      - ./timereporter-api/db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql

  api:
    build:
      context: ./timereporter-api
      target: production
    container_name: api
    depends_on:
      - db
    ports:
      - 3000:3000
    env_file:
      - ./timereporter-api/.env
    volumes:
      - ./timereporter-api/src:/app/src

  ui:
    container_name: ui
    build: ./timereporter-ui
    depends_on:
      - api
    ports:
      - 80:80
    # volumes:
    #   - ./timereporter-ui:/src
    #   - /

volumes:
  db:
